### PR TITLE
Fix incorrect reference to local roles blueprint

### PR DESCRIPTION
**Pull request by mgrbyte**

### CODE REVIEW

**Comment by mgrbyte** [comment]
supercedes #16.

**Comment by ale-rt** [comment]
Thanks @mgrbyte!

**Comment by mgrbyte** [comment]
@ale-rt You appear to have closed this w/o merge?!

**Comment by ale-rt** [comment]
Sorry :( Stupid me

**Comment by mgrbyte** [comment]
:stuck_out_tongue_winking_eye:

**Pull request merged**
