### PR TITLE
Take Dexterity content-types into account when setting the workflow h…

### PR DESCRIPTION
**Pull request by erral**
…istory. Refs #15

### CODE REVIEW

**Comment by djowett** [comment]
@erral this fix was helpful - but needed the above commit to get it working for me.  Can you review with a view to merging?

**Comment by erral** [comment]
Looks good to me. I guess I was using a previous version of c.transmogrifier when I sent the PR.

**Comment by djowett** [comment]
@erral great! Not sure exactly the difference between traverse() and what I replaced.

Anyway, do you mind cherry picking my commit to your branch (for continuity), and I will then merge the PR?

**Comment by erral** [comment]
Done!

**Comment by djowett** [comment]
done too!

**Pull request merged**
